### ISSUE TITLE
Is there any way I could enable encryption/descryption on the data that I am trying to store?

### ISSUE THREAD

**Issue by CuriousDrive** [Blazored/SessionStorage#10]
Thanks for the implementing this. SessionStorage has been very helpful in maintaining user's state in my Blazor application.

Although, is there any way I can Encrypt and Decrypt data stored in browser storage?

**Comment by chrissainty** [comment]
Yes, you could encrypt the data before saving it to session storage - it's not part of this library, however, so you would need to implement that yourself. The only thing I would ask is why/what do you need to store? 

The client is simply not secure, encrypting the data at best is only going to slow someone down. If the data is sensitive enough to warrant encryption then shouldn't you be storing it server-side?

**Comment by CuriousDrive** [comment]
Thanks for replying Chris.
I am getting JWT token from my API and storing that in session storage. Is that a good idea?

If not, where should I store it? Where do people normally store it?

**Comment by chrissainty** [comment]
That's what most people do with their JWTs, I tend to use local storage myself so it persists across session but that's down to your requirements. I'm no security expert mind you but all of the client-side apps I've built (I used to develop AngularJS and Angular apps prior to Blazor) have always done this.

**Comment by CuriousDrive** [comment]
Ok. That makes me feel better. 

Sorry for raising this as an issue. This is the 1st issue, I have raised on GitHub. It's nice talking to you and being part of the community. Thanks for your efforts.

**Comment by HopInTheCloud** [comment]
Using LocalStorage or SessionStorage without encryption or some kind of protection, makes your tokens vulnerable to Cross Site Scripting (XSS)

**Comment by chrissainty** [comment]
@HopInTheCloud Even with encryption they are vulnerable as they ultimately reside on the client. Encryption will only slow a motivated party down.

**Comment by HopInTheCloud** [comment]
I do realize, when you are targeted, they will try and compromise your data in the browser storage but at least make it difficult for them.
Maybe look at some like "ASP.NET Core Data Protection" to include in your library.
I am currently using your library with "ASP.NET Core Data Protection" to encrypt the data and then store it with SessionStorage.

I also just want to add that you have created a great library which I am using in my applications.

**Comment by chrissainty** [comment]
@HopInTheCloud I appreciate what you're saying, please don't think I don't. My concern is this, if I offer encryption in this library and someones app gets hacked, I don't want to take that responsibility. The Blazor team are releasing the ProtectedLocalStorage package in the next preview for .NET5 and, if I'm honest, I think people will start to move over to that as it's "official" from MS.

**Comment by HopInTheCloud** [comment]
Yes. I read about the upcoming ProtectedLocalStorage as well. The only reason I did not mention it, is because it is still a experimental project. When MS eventually releases it, everybody will be using that, you are correct.

**Comment by chrissainty** [comment]
> When MS eventually releases it, everybody will be using that, you are correct.

Which makes it difficult for me to justify the time to add the feature. Not much support for the open source community in the .NET world at times.

**Comment by GitHubington** [comment]
Some kind of options feature/middleware would be good...
```
builder.Services.AddBlazoredSessionStorage(options => {
	options.OnSet(data => { return data.Base64Encode(); });
	options.OnGet(data => { return data.Base64Decode(); });
});
```
Then we can roll our own.
