### ISSUE TITLE
unable to display the value of session storage in the example

### ISSUE THREAD

**Issue by ojorma** [Blazored/SessionStorage#11]
```
<span>@Name</span>

@code { 
    public string Name { get; set; } 
    protected override async Task OnAfterRenderAsync()
    {
        await sessionStorage.SetItemAsync("name", "John Smith");
        var name = await sessionStorage.GetItemAsync<string>("name");
        Name = name;
    }
}
```

From this example, there is no way Name variable. When debugging you will see the value been set but the UI is not been updated. It's a serverside blazor application

**Comment by chrissainty** [comment]
I can't see any obvious reason this code shouldn't work. What errors are you seeing? Have you stepped through the code while debugging? If so what happened?

**Comment by ojorma** [comment]
the name john smith doesnt display. anything i do in the OnAfterRenderAysnc doest change the UI

**Comment by ojorma** [comment]
first thing i actually noticed that i changed 
protected override async Task OnAfterRenderAsync() does not exist
![image](https://user-images.githubusercontent.com/17591360/74200083-41a61500-4c66-11ea-9f30-c41341648dd0.png)

So im actually using 
protected override async Task OnAfterRenderAsync(bool firstRender)

![image](https://user-images.githubusercontent.com/17591360/74200130-61d5d400-4c66-11ea-8074-436313f0c53c.png)

**Comment by ojorma** [comment]
`@page "/counter"
@inject Blazored.SessionStorage.ISessionStorageService sessionStorage
<h1>Counter</h1>

<p>Current count: @currentCount</p>

<p>@Name</p>
<button class="btn btn-primary" @onclick="IncrementCount">Click me</button>

@functions  {
    private int currentCount = 0;
    private string Name;
    private void IncrementCount()
    {
        currentCount++;
    }



       protected override async Task OnAfterRenderAsync(bool firstRender)
    
    {
        await sessionStorage.SetItemAsync("name", "John Smith");
        var name = await sessionStorage.GetItemAsync<string>("name");
        Name = name;
        base.OnAfterRender(firstRender);
    }
}
`

**Comment by chrissainty** [comment]
I doubt this is having an effect on anything but you shouldn't be using `functions`, that is a Razor Pages feature. For Blazor components you should be using `code`.

Could you try adding a `StateHasChanged` call after you set the `Name` property.

**Comment by ojorma** [comment]
StateHasChanged, that did it. me using code and functions is just me trying everything i can think of. Thanks problem solved.
