### ISSUE TITLE
[Feature Request] Serialize with lower case / camelCase

### ISSUE THREAD

**Issue by kristof12345** [Blazored/SessionStorage#15]
**Is your feature request related to a problem? Please describe.**
I would like to access the sessionStorage data from JS code, which expects camelCase syntax for field names.

**Describe the solution you'd like**
It'd be great to have an option to setup serialization options. Eg. in startup with an enum like "Serialization.Camelcase". 

**Describe alternatives you've considered**
Using camelCase in .net.

**Additional context**
Great library! Thanks.

**Comment by chrissainty** [comment]
I agree this would be a good setting to expose. I think the best scenario would be to allow the developer to configure the JSON options for the serializer and then we just load those.
