### ISSUE TITLE
[Question] Is it possible to store complex objects or just strings?

### ISSUE THREAD

**Issue by nadcraker** [Blazored/SessionStorage#16]
Specifically I am trying to store a [`WindowsIdentity.AccessToken`](WindowsIdentity.AccessToken).

Here is my `_Host.cshtml.cs` file
```
public class HostAuthenticationModel : PageModel
{
    public async Task<IActionResult> OnGet()
    {
        if (User.Identity.IsAuthenticated)
        {
            var windowsIdentity = (WindowsIdentity)User.Identity;
            AccessToken = windowsIdentity.AccessToken;
        }
        return Page();
    }

    public SafeAccessTokenHandle AccessToken { get; set; }
}
```
Here is my `app.razor` file
```
    [Parameter]
    public Microsoft.Win32.SafeHandles.SafeAccessTokenHandle AccessToken { get; set; }

    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        if (firstRender)
        {
            // Persist the AccessToken to local storage
            await sessionStorage.SetItemAsync("win_access_token", AccessToken);
        }
    }
```

And here I try to retrieve it in a razor component: `var accessToken = await sessionStorage.GetItemAsync<Microsoft.Win32.SafeHandles.SafeAccessTokenHandle>("win_access_token");`

I successfully retrieve the token, but its properties are not the same as when I stored them. Is something not surviving the serialization process?

**Comment by chrissainty** [comment]
HI @nadcraker, we serialise the objects you pass using the new System.Text.Json library. We've found there can be some issues depending on the object you're passing into Session Storage.

When you say the properties are not the same, what's changed. Can you provide an example?

**Comment by nadcraker** [comment]
Actually I think the storing and retrieving of the SafeAccessTokenHandle was just fine. The reason that some properties were different is because the handle was no longer valid, which is no fault of SessionStorage.
