### ISSUE TITLE
[Question] How to read browser session storage?

### ISSUE THREAD

**Issue by HenningNT** [Blazored/SessionStorage#17]
When I try to read something from the session storage managed by the browser I get a json deserializing exception. I guess the GetItemAsync<T> tries to deserialize the file?

How should I go about reading some data from the session storage which hasn't been serialized to json?

(The goal is to read an access token stored in the session storage, which is stored by the browser)

**Comment by HenningNT** [comment]
I looked into the source and found an answer:
var token = await _jSRuntime.InvokeAsync<string>("sessionStorage.getItem", "msal.idtoken");

:-)

**Comment by chrissainty** [comment]
Sorry I didn’t get to this sooner but glad you found the answer.
