### ISSUE TITLE
Method not found: 'System.Threading.Tasks.Task Blazored.SessionStorage.ISessionStorageService.SetItemAsync(System.String, System.Object)'

### ISSUE THREAD

**Issue by tripleacoder** [Blazored/SessionStorage#20]
In version 1.0.12, I get the exception:

System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task Blazored.SessionStorage.ISessionStorageService.SetItemAsync(System.String, System.Object)'.

when calling

await this.sessionStorage.SetItemAsync(propertyName, value);

Version 1.0.11 is working fine.

**Comment by chrissainty** [comment]
Hi @tripleacoder, I've run the sample projects and everything appears to be working as expected. Can you provide a repro of the issue so I can run it and understand where it's going wrong?

**Comment by chrissainty** [comment]
As there hasn't been any further info provided. I'm going to close this issue.

**Comment by chrissainty** [comment]
Thanks @tripleacoder. There possibly was a breaking change between the versions we let slip through hence the error you were seeing.

**Comment by JalilSabri** [comment]
I use version 4.0.0 and have the same bug when I call LocalStorage methods. I can't trace the code that the container LocalStorage method.
for example, I have this message in the browser console:
Method not found: 'System.Threading.Tasks.ValueTask`1<System.String> Blazored.LocalStorage.ILocalStorageService.KeyAsync(Int32)

**Comment by chrissainty** [comment]
@JalilSabri If you can provide a repro for the issue I can look into this.

**Comment by JalilSabri** [comment]
thank you for your following-up,
fortunately, I just updated it to version 4.4.0, and the issue is fixed.
