### ISSUE TITLE
[Bug] Miss ContainKeyAsync

### ISSUE THREAD

**Issue by walteriermano** [Blazored/SessionStorage#22]
**Describe the bug**
Miss the Method ContainKeyAsync , in documentation is present but not in the code

**Hosting Model (is this issue happening with a certain hosting model?):**
 - Blazor Server

**Comment by chrissainty** [comment]
Hey @walteriermano 

Apologies I’ve merged the PR which added this functionality but I forgot to release it. I’m in the process of changing all of the CI/CD over to GitHub Actions for all Blazored Projects so this type of thing is easier to manage. 

If you can bare with me I’ll get this released ASAP.

**Comment by walteriermano** [comment]
Thanks

**Comment by drma-dev** [comment]
@chrissainty 

I was looking for just that functionality now. Did you have a problem with the code not to be released?
