### ISSUE TITLE
[Question] Blazored.LocalStorage and Blazored.SessionStorage store the same values differently

### ISSUE THREAD

**Issue by ajruckman** [Blazored/SessionStorage#23]
Hi, I have some code where I want to be able to store a value in either Session Storage or Local Storage. I am using both of your libraries to access them. I expected the data stored to be in exactly the same format in both, no matter which "provider" I used.

I have an interface like this:
```c#
    public interface IStorageProvider
    {
        Task    SetItemAsync<T>(string key, T data);
    }
```
and 2 classes like these:
```c#
    public class LocalStorageProvider : IStorageProvider
    {
        private readonly ILocalStorageService _localStorage;
        ...
        public Task SetItemAsync<T>(string key, T data) => _localStorage.SetItemAsync(key, data);
    }

    public class SessionStorageProvider : IStorageProvider
    {
        private readonly ISessionStorageService _sessionStorage;
        ...
        public Task SetItemAsync<T>(string key, T data) => _sessionStorage.SetItemAsync(key, data);
    }
```

But the values is stored in Local/Session Storage are not the same. Here is what gets stored in Session Storage when I set a JSON string:
```"{\u0022FilterValue\u0022:\u0022\u0022,\u0022Shown\u0022:true,\u0022SortDirection\u0022:0,\u0022SortIndex\u0022:0}"```
And  the same value stored in Local Storage:
```{"FilterValue":"","Shown":true,"SortDirection":0,"SortIndex":0}```

Not sure if I am doing something wrong or not... 
Thanks!

**Comment by chrissainty** [comment]
Thanks for raising this @ajruckman. I think there has been some drift in functionality between the two libraries over time. This is something that will be addressed and I'm exploring options to stop this happening again in the future.
