### ISSUE TITLE
Reading 'existing / normal' values from session storage is not possible

### ISSUE THREAD

**Issue by StefH** [Blazored/SessionStorage#24]
The current implementation from `GetItemAsync<string>("key")` reads the value as string, but also deserializes using JSON.

This means that I cannot use GetItemAsync for reading existing / normal string-values from the SessionStorage (these values are added to the SessionStorage by other code)

Proposals can be:
1. In case deserializing the string value into json object fails, just return the string value
2. Add another method like `GetLegacyStringAsync("key")` or `GetStringAsync("key")`

What do you think?

**Comment by chrissainty** [comment]
@StefH Something like this (https://github.com/Blazored/LocalStorage/pull/88) perhaps? :)

**Comment by StefH** [comment]
Indeed. The same idea.

Can you implement it in this project and the local storage?

**Comment by chrissainty** [comment]
Yes, once we have it in local storage we’ll implement it here as well.

**Comment by StefH** [comment]
@chrissainty I see that the code for LocalStorage is merged.

Can you please apply the same fix for this project?

**Comment by chrissainty** [comment]
@StefH I'm looking to merge the codebases for these two libraries so keeping features in sync isn't such a drain. Once this is done then this feature will be available.

**Comment by StefH** [comment]
@chrissainty That's a good idea, just keep me posted on this when it's ready.
