### ISSUE TITLE
How to check the session is null or not

### ISSUE THREAD

**Issue by imprathamesh** [Blazored/SessionStorage#25]
How do i check the session is null or not. 
like 
int customerid;
if(sessionstorage.GetItemAsync<int>("CustomerID") == null)
{
nm.Navigate("/login");
}
else
{
customerid = sessionstorage.GetItemAsync<int>("CustomerID");
}

this is not working. is there any problem? please help me.

**Comment by chrissainty** [comment]
Hi @imprathamesh,

You could do the following to check for a value in Session Storage.

```csharp
var customerID = sessionstorage.GetItemAsync<int>("CustomerID");
if (customerID == 0)
{
    nm.Navigate("/login");
}

// Continue with happy path logic
```
