### ISSUE TITLE
Update documentation on Usage (Blazor Server)

### ISSUE THREAD

**Issue by lonwabogiqwa** [Blazored/SessionStorage#29]
This is just a comment that if you set the Blazor app render-mode to server, you do not need to wait for OnAfterRenderAsync. You can inject and use session storage on OnInitializedAsync or some other handler.
`<app><component type="typeof(App)" render-mode="Server" /></app>`

**Comment by chrissainty** [comment]
I'm surprised by this. However we won't be updating the docs as the official guidance is to perform JS interop in the OnAfterRender lifecycle method, only. 

I'll have a look into this when I have time as thud shouldn't work on Blazor Server.
