### ISSUE TITLE
To provide option to use custom json serialize like newtonsoft

### ISSUE THREAD

**Issue by surpavan** [Blazored/SessionStorage#30]
The system.text.json is not able to serialize many types where they are nested, atleast in my case. But newtonsoft json is able to serialize.

It would be great if there is an option to choose between Microsoft provided one and custom provider like newtonsoft.

Below is my middleware like implementation:
```
    public class BlazoredConverter
    {
        Blazored.SessionStorage.ISessionStorageService _sessionStorageService;
        public BlazoredConverter(Blazored.SessionStorage.ISessionStorageService sessionStorageService)
        {
            _sessionStorageService = sessionStorageService;
        }


        public async Task<T> Get<T>(string fetchForKey)
        {
            var t = await _sessionStorageService.GetItemAsync<string>(fetchForKey);
            if (t != null)
            {
                return Newtonsoft.Json.JsonConvert.DeserializeObject<T>(t);
            }
            else { return default(T); }
        }

        public async Task<bool> Set<T>(string keyname, T TValue)
        {
            try
            {
                string r = Newtonsoft.Json.JsonConvert.SerializeObject(TValue);
                await _sessionStorageService.SetItemAsync<string>(keyname, r);
                return await Task.FromResult(true);
            }
            catch (Exception)
            {
                return await Task.FromResult(false);
            }
        }
    }
```

**Comment by chrissainty** [comment]
Yes I agree @surpavan. This is something which has been proposed on the Local Storage version of this library as well, I'm currently looking at a way of blending these two libraries into a single code base so features become available on both versions simultaneously. At that point this will be available so please bare with me if that's ok.

**Comment by surpavan** [comment]
>  At that point this will be available so please bare with me if that's ok.

We like your code, it made work way more simple and easy.  Thank you for that.

**Comment by tripleacoder** [comment]
This would be great to have. 
Right now, the model classes in my Blazor projects are full of workarounds because of the limitations of the .NET serializer.
