### ISSUE TITLE
[Bug] GetItemAync hangs

### ISSUE THREAD

**Issue by BrianJose** [Blazored/SessionStorage#31]
I am using Blazored.Session storage in my blazor server application. Both the setItemAsync getItemAsync work fine in debug and release mode if I have the debugger attached. When I host the web page and run the release version without the debugger attached the getItemAsync hangs. Any idea why this might be happening especially since it does not hang when the debugger is attached?

**Comment by chrissainty** [comment]
Hi @BrianJose, I've not heard of this one before. Can you provide a minimal repro of the issue and I can have a look into it.
