### ISSUE TITLE
[Bug] Cannot use library with .NET 5 RC1

### ISSUE THREAD

**Issue by SommerEngineering** [Blazored/SessionStorage#32]
I am currently testing .NET 5.0 RC1. Unfortunately I had to find out that this library is not compatible with `<TargetFramework>net5.0</TargetFramework>`. Could you create a pre-release that is compatible? Thanks 🙂

**Comment by chrissainty** [comment]
Hi this library does work with .NET5 as is. You need to be running the latest RC and the preview version of Visual Studio.
