### ISSUE TITLE
[Bug]GetItemAsync and SetItemAsync throw System.Threading.Tasks.TaskCanceledException: 'A task was canceled.'

### ISSUE THREAD

**Issue by tripleacoder** [Blazored/SessionStorage#33]
In my new app, I'm trying to use SessionStorage to store larger graphs of objects (a few hundreds).

However, I often get 'A task was canceled' from GetItemAsync and SetItemAsync. Also, Blazor shows the message "Attempting to reconnect to server" both when doing local debugging and when deployed to an IIS server.

What is the performance of SessionStorage when storing and retrieving 100s of objects? Is it advisable to do so?

Hosting Model:
 - Blazor Server

**Comment by chrissainty** [comment]
Hi @tripleacoder, the quick answer to your question is I don't know. When large amounts of data are stored in browser stroage (local or session) people seem to be finding issues like the one you've raised. I'm not sure yet if this is an issue with browser storage or something to do with Blazor/this library. Could you try and produce a minimal repro of the issue so I can debug it? So far we haven't been able to do that/has someone will to do it.

**Comment by tripleacoder** [comment]
I can repro it in my project right now, 100% of the time by calling SetItemAsync with a null argument.
It happens in an EditForm OnValidSubmit handler...

**Comment by chrissainty** [comment]
Ok, but I need a working repro project. What you've just described is also different to your initial issue.

**Comment by tripleacoder** [comment]
No, it seems related... 

If I call SetItemAsync first with a complex object with 100 child objects it works. 
But then I can repro the timeout if I call SetItemAsync (using the same key) with null, or a different, or the same object.

Could the problem be caused by the code that is erasing the previous entry?

**Comment by tripleacoder** [comment]
This bug appears to be related to shared nodes in an object tree. I'm working on a repro project now.

**Comment by tripleacoder** [comment]
I have made a repro project:
https://github.com/tripleacoder/BlazorApp3

**Comment by tripleacoder** [comment]
Can you repro it..?

**Comment by larspage** [comment]
Was this resolved?  What if you use JSON or serialization?

**Comment by tripleacoder** [comment]
Hi Chris,
Can this be given higher priority. It seems there is no real workaround and the error can appear suddenly and unpredictably, even with smaller object graphs.

**Comment by chrissainty** [comment]
Hi @tripleacoder. Apologies this one slipped off my radar. I'll take a look at this at the weekend.

**Comment by tripleacoder** [comment]
The bug is still there after upgrading to v. 2.1.0.
When I run the repro project I can reproduce the error 100% of the time.

**Comment by tripleacoder** [comment]
The bug is also present when using the Newtonsoft JSON serializer instead of the default one.

**Comment by tripleacoder** [comment]
@chrissainty 
Hi Chris, will you re-open this issue as I believe the problem is still there after the code changes.
