### ISSUE TITLE
[Question] Error: The circuit has closed due to an error.

### ISSUE THREAD

**Issue by lxman** [Blazored/SessionStorage#34]
So, I have been using this package without issue. In a component I have designed I am calling SetItemAsync in the dispose method so that when it comes up on another page I can restore the state. I have suddenly noticed that this no longer seems to work. In particular, when I refresh the page with the component, I see the above error.
I'm using this with Blazor server with .net core 3.1. Has something recently changed that would break this?

**Comment by chrissainty** [comment]
Apologies, I missed this issue being filed. Are you still having a problem? There have been no changes that would have caused this, as far as I'm aware.

**Comment by lxman** [comment]
No problem - I have since reworked the page - it appears that the issue may
be me trying to write to sessionstorage inside of a dispose method. Since I
have reworked the code not to do that the error has gone away.

**Comment by chrissainty** [comment]
That's good news, I'll go ahead and close this issue then.
