### ISSUE TITLE
Blazored session storage to work for objects.

### ISSUE THREAD

**Issue by ezdsdeveloper** [Blazored/SessionStorage#35]
Storing an object works just fine

Getting that object and deserializing it breaks
.
  Person person = await sessionStorage.GetItemAsync<Person>("People");

I think this is related to another contributor mentioning system.text.json and the inherent issues with that dependency.

Just need a way to store objects in blazor for the entire session. 

Using a singleton wont work obviously. 

Using a scoped class seems to work until the class is injected on another page, and starts fresh again... ughhh

**Comment by chrissainty** [comment]
Hi, could you provide some details about how it break? An error message for example? Even better would be a minimal repro of the issue.

**Comment by jacobdenis** [comment]
It seemed it's on my app settings since I've used singleton for my services. SessionStorage is working fine. Thank you. for your assistance
