### ISSUE TITLE
[Question] Getting error when storing complex object

### ISSUE THREAD

**Issue by darrylluther** [Blazored/SessionStorage#37]
I'm attempting to store a complex object (EF Core entity) that has navigation properties which refer back to the parent entity. I've added a [JsonIgnore] attribute to my entities and my default JsonSerializerSettings ReferenceLoopHandling property is set to ReferenceLoopHandling.Ignore, but I continue to get the error:

`Error: System.Text.Json.JsonException: A possible object cycle was detected. This can either be due to a cycle or if the object depth is larger than the maximum allowed depth of 64. Consider using ReferenceHandler.Preserve on JsonSerializerOptions to support cycles.`

I feel like I must be missing something, but I'm not sure what. Any ideas?

**Comment by chrissainty** [comment]
I've not come across this error myself. Could you create a repro of the issue on GitHub and post a link to it so we can run it and try and figure out what might be going on?

Could I ask why you're storing EF entities on the client? That seems like it could be dangerous.

**Comment by darrylluther** [comment]
It's difficult to provide a repo because it's likely how EF Core structures the data that is causing the error. However, you are right that storing EF entities on the client could be dangerous. I was simply hoping to avoid another call to the database in the case where a user refreshes the screen. I've opted to store the ID of the record being edited and I just pull it from the DB on a refresh.
