### ISSUE TITLE
[Question] Session per browser

### ISSUE THREAD

**Issue by jacobdenis** [Blazored/SessionStorage#38]
**Please be sure to check the readme file before raising an issue.**
Hi, i am currently experiencing issue regarding the session where when i login in  mozilla  and then i will login other account in the google chrome when i refresh my mozilla browser it show the account that i login in the chrome browser

here is my code
![image](https://user-images.githubusercontent.com/28717802/100355528-e5fa1c00-302c-11eb-9627-3ccb4ea19468.png)

**Comment by chrissainty** [comment]
I'm not really sure how this could happen. Each browsers storage is isolated. Are you using Blazor Server or Wasm? Could you provide some more code to help understand what is going on? There is little we can do with the current example.

**Comment by jacobdenis** [comment]
It seemed it's on my app settings since I've used singleton for my services. SessionStorage is working fine. Thank you. for your assistance
