### ISSUE TITLE
[Feature Request] Miss ContainKeyAsync

### ISSUE THREAD

**Issue by drma-dev** [Blazored/SessionStorage#41]
I know you already have a ticket open, it's just a reminder.

Is there anything missing to upload this update? I can help with something?

**Comment by chrissainty** [comment]
@drma-dev My apologies it turns out the PR was never merged. It was closed when we switched default branch names. If you would like to submit a new PR with the functionality (you can copy the original one if you wish). I will get it merged and released.

**Comment by drma-dev** [comment]
Done. I didn't get to test it, I just copied what was done.
