### ISSUE TITLE
[Question] Using System.Text.Json.JsonSerializer.SerializeToUtf8Bytes

### ISSUE THREAD

**Issue by adrianwright109** [Blazored/SessionStorage#45]
Hi,

I have a list of complex objects that are rendered in a Telerik Blazor Grid. When I select items in the grid the grid's OnItemSelected event sends an`IEnumerable<T>` of all the selected items in the grid.

I can save this to a property in the Blazor component.

What I want to be able to do is persist that data so that if a user navigates away from the page that has the grid and then returns back I can populate the grid and select the items in the grid that were selected before.

I thought I would try and use `System.Text.Json.JsonSerializer.SerializeToUtf8Bytes` as it's suppose to be quicker than storing as a JSON string and therefore I'm also assuming it might take up less storage space in the browser's session storage.

Would I be able to use `System.Text.Json.JsonSerializer.SerializeToUtf8Bytes` to create a `byte[]` then store and retrieve that `byte[]` array like this:
```C#
// Local page property with selected grid items
public IEnumerable<ComplexObj> SelectedItems { get; set; }

// Convert selected items of type ComplexObj to
var jsonUtf8Bytes = JsonSerializer.SerializeToUtf8Bytes<IEnumerable<ComplexObj>>(SelectedItems, new JsonSerializerOptions());

// Store byte array to browser session storage
await sessionStorage.SetItemAsync("selectedItems", jsonUtf8Bytes);

// Retrieve byte array from session storage
var jsonUtf8Bytes = await sessionStorage.GetItemAsync<byte[]>("selectedItems");

// Convert byte array to readonly span of bytes
var readOnlySpan = new ReadOnlySpan<byte>(jsonUtf8Bytes);

// DeSerialize span back to list of ComplexObj type
var obj = JsonSerializer.Deserialize<IEnumerable<ComplexObj>>(readOnlySpan);
```

**Comment by chrissainty** [comment]
Hi @adrianwright109. The browsers session storage is only capable of storing string values. So that is the only thing you need to factor in here. I'm curious if you've hit any speed issues with the default serialization or if you're just expecting them?

**Comment by adrianwright109** [comment]
I'm more worried about exceeding the browser's session storage limit as these Telerik grids can have up to 10,000 rows in them. Potentially 10,000 rows could be selected and serializing a list of that many into a JSON string could exceed the limit. Unfortunately the grid needs the full objects to set the selected items, not just an ID.

Other option which I might have to do is store a unique ID into session storage then retrieve them from session storage and the use them to query the database to build up the list of selected items from the IDs.

**Comment by chrissainty** [comment]
I see what you're saying. Session storage will hold up to around 5MB. I think storing the ID's with a call back to the DB is probably a more robust option.

As there isn't anything to do here I'm going to close this issue.
