### ISSUE TITLE
[Feature Request] Cancellation Token support

### ISSUE THREAD

**Issue by Jagreaper** [Blazored/SessionStorage#48]
I'm was trying to create a common interface to bridge the two implementations of your LocalStorageSession and SessionStorageService. However, whilst the interface for the LocalStorageService has support for cancellation tokens in its methods, the storage service does not.

I would like to see CancellationToken support integrated with this library to bring it further into parity with the LocalStorage library.

**Comment by chrissainty** [comment]
Please feel free to raise a PR for this feature.
