### ISSUE TITLE
Could the dependency on bUnit.Core be removed?

### ISSUE THREAD

**Issue by andrew-tevent** [Blazored/SessionStorage#50]
I've just found that our app is shipping `bUnit.Core` and on inspection, tracked it down to Blazored.SessionStorage.

Could this be removed from the production code perhaps?

You could still have a `TestContentBase` extension method in the Tests project, but it could create a `ServiceCollection`, call the production `AddBlazoredSessionStorage` to register all the DI (as it would in a production app) and then copy all the registrations over to the TestContext (switching out the `IStorageProvider`).  That way you wouldn't need the duplicate DI registrations too!

**Comment by chrissainty** [comment]
Thanks for raising this. We had this problem in Local Storage and we've created a separate test package and we'll do the same thing here.
