### ISSUE TITLE
Sessionstorage service not storing the value

### ISSUE THREAD

**Issue by komirineni** [Blazored/SessionStorage#7]
Blazor Server app am calling below method in login page  store username
     await sessionStorage.SetItemAsync("Name",CurrentUser.Username);

and am using below method to retireive the save session name value but it is always getting null  
var name = await _sessionStorageService.GetItemAsync<string>("Name");

Please let me know the reasons why session not storing in my blazer server app

**Comment by chrissainty** [comment]
Hey, by the looks of it you're not specifying the type to deserialize the value to. Try something like this.

```csharp
var name = await _sessionStorageService.GetItemAsync<string>("Name");
```

**Comment by komirineni** [comment]
I have tried that also so am getting null value.

**Comment by chrissainty** [comment]
Can you provide a repro of the issue with the minimum amount of code possible, please?

**Comment by komirineni** [comment]
//Customautstate provider   
 public class CustomAuthStateProvider :  AuthenticationStateProvider
    {
        //public UserModel CurrentUser { get; set; }
        //ClaimsIdentity identity = new ClaimsIdentity(new[] { new Claim(ClaimTypes.Name, "Admin") }, "Custom");
        private ISessionStorageService _sessionStorageService;
        public CustomAuthStateProvider(ISessionStorageService sessionStorageService)
        {
            _sessionStorageService = sessionStorageService;
        }
        public async override Task<AuthenticationState> GetAuthenticationStateAsync()
        {

            ClaimsIdentity identity;
            var name = await _sessionStorageService.GetItemAsync<string>("Name");
            if (name != null)
            {
                identity=new ClaimsIdentity(new[] { new Claim(ClaimTypes.Name, name) }, "Custom");
             
                return await Task.FromResult(new AuthenticationState(new ClaimsPrincipal(identity)));
            }
            else
            {
                if(false)
                identity = new ClaimsIdentity(new[] { new Claim(ClaimTypes.Name, "Admin") }, "Custom");
                else
                identity = new ClaimsIdentity();
                return await Task.FromResult(new AuthenticationState(new ClaimsPrincipal(identity)));
            }
         
        }

        public void MarkUserAsAuthentiated(string username)
        {
            ClaimsIdentity identity = new ClaimsIdentity(new[] { new Claim(ClaimTypes.Name, username) }, "Custom");
            NotifyAuthenticationStateChanged(Task.FromResult(new AuthenticationState(new ClaimsPrincipal(identity))));

        }

//Login screen code:

       ((CustomAuthStateProvider)authstateprovider).MarkUserAsAuthentiated(Username);
            await sessionStorage.SetItemAsync("Name",Username);

**Comment by chrissainty** [comment]
As you're using a Blazor Server app there is a chance that the code is being run before the connection to the browser is up and working. Could you try putting some test code in a components `OnAfterRender` method, inside of a check for `FirstRender`. If that works then it's a timing issue with Blazor Server and when this code gets run.

**Comment by komirineni** [comment]
We are calling it on button click that means after component load where we are calling session storage to store the value.

**Comment by chrissainty** [comment]
Ah ok. 

In that case, could you provide the code as a fully working sample, please? I appreciate you adding the snippet you have above but I don't have the free time to try and patch it into an app somewhere and get it to run. Thanks.

**Comment by chrissainty** [comment]
As I've not heard anything back I'm going to close this issue. Please feel free to re-open if you can provide a working repro.
