### ISSUE TITLE
How do I removed a variable stored in local storage from a Blazor Server App?

### ISSUE THREAD

**Issue by Keenan-Softserve** [Blazored/SessionStorage#79]
The README only shows an example of setting a value in local storage but not removing it.

**Comment by chrissainty** [comment]
The available APIs are listed at the bottom of the README. There is also an example of removing a value in the Sample apps.

https://github.com/Blazored/SessionStorage/blob/092ce10e7c23ff145553266952c534dc31a4b5e0/samples/BlazorWebAssembly/Pages/Index.razor#L116

**Comment by Keenan-Softserve** [comment]
Thanks but that's a WASM app, that's why I specified that I'm asking how to do this in a Blazor Server app.

**Comment by chrissainty** [comment]
There is no difference between WebAssembly and Server, they both use the same APIs. There is also a Server project in the samples folder!
