### ISSUE TITLE
Typo In README.md

### ISSUE THREAD

**Issue by DaisyDave** [Blazored/SessionStorage#8]
Just a minor issue but in the [Usage (Blazor WebAssembly)](https://github.com/Blazored/SessionStorage#usage-blazor-webassembly) synchronous example.

The interface name is incorrect. `ISyncStorageService` is used but the actual interface name is `ISyncSessionStorageService`

Once I got over that it seems to be working great for me.

**Comment by chrissainty** [comment]
Thanks for spotting this, @DaisyDave. It's now sorted.
