### ISSUE TITLE
[Question] Get sessions values in ASP Controllers

### ISSUE THREAD

**Issue by ItsTheSky** [Blazored/SessionStorage#84]
Hi there!
I'm currently injecting the `ISessionStorageService` in my Blazor pages, and then using the `OnAfterRenderAsync` method to fetch my data. Although using `OnInitializedAsync` throws an error, that is logical, how can I manage sessions in an ASP Controller? 
I tried using the `[Inject]` field declaration and giving the service in my controller's constructor, but I still have the "JavaScript not loaded" error (Blazor is not yet rendered). 
Any ideas? Here's my current code if it can helps anyhow:

```csharp
using Microsoft.AspNetCore.Mvc;
using PatreonResources.Components.Utilities;

namespace PatreonResources.Components.Pages;

[ApiController]
[Route("api")]
public class DownloadController : ControllerBase
{
    
    [HttpGet, DisableRequestSizeLimit]
    [Route("download")]
    public async Task<IActionResult> Download(string ResourceId)
    {
        var resource = ResourceData.GetResources().Result.FirstOrDefault(x => x.Id == ResourceId);
        if (resource is null)
            return NotFound();
        
        var file = Path.Combine("Resources", $"{ResourceId}.jar");
        
        var memory = new MemoryStream();
        await using(var stream = new FileStream(file, FileMode.Open))
        {
            await stream.CopyToAsync(memory);
        }
        
        memory.Position = 0;
        return File(memory, "application/octet-stream", $"{resource.Name} v{resource.Version}.jar");
    }
}
```

**Comment by chrissainty** [comment]
Hi @ItsTheSky, session storage exists on the clients browser. You're trying to access it from a method running on the server. This is essentially the same as you trying to access the file system of another machine over the internet.

What you're attempting just isn't possible. If you need some state from the client in your server-side code you need to keep that state on the server.
